/* 
 * Vericred API
 *
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
<cost-share>     ::= <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> <tier-limit> "/" <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> "|" <benefit-limit>
<tier>           ::= "In-Network:" | "In-Network-Tier-2:" | "Out-of-Network:"
<opt-num-prefix> ::= "first" <num> <unit> | ""
<unit>           ::= "day(s)" | "visit(s)" | "exam(s)" | "item(s)"
<value>          ::= <ddct_moop> | <copay> | <coinsurance> | <compound> | "unknown" | "Not Applicable"
<compound>       ::= <copay> <deductible> "then" <coinsurance> <deductible> | <copay> <deductible> "then" <copay> <deductible> | <coinsurance> <deductible> "then" <coinsurance> <deductible>
<copay>          ::= "$" <num>
<coinsurace>     ::= <num> "%"
<ddct_moop>      ::= <copay> | "Included in Medical" | "Unlimited"
<opt-per-unit>   ::= "per day" | "per visit" | "per stay" | ""
<deductible>     ::= "before deductible" | "after deductible" | ""
<tier-limit>     ::= ", " <limit> | ""
<benefit-limit>  ::= <limit> | ""
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Vericred.Model
{
    /// <summary>
    /// DrugCoverage
    /// </summary>
    [DataContract]
    public partial class DrugCoverage :  IEquatable<DrugCoverage>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DrugCoverage" /> class.
        /// </summary>
        /// <param name="PlanId">Health Insurance Oversight System id.</param>
        /// <param name="DrugPackageId">NDC package code.</param>
        /// <param name="MedId">Med ID.</param>
        /// <param name="QuantityLimit">Quantity limit exists.</param>
        /// <param name="PriorAuthorization">Prior authorization required.</param>
        /// <param name="StepTherapy">Step Treatment required.</param>
        /// <param name="Tier">Tier Name.</param>
        public DrugCoverage(string PlanId = null, string DrugPackageId = null, int? MedId = null, bool? QuantityLimit = null, bool? PriorAuthorization = null, bool? StepTherapy = null, string Tier = null)
        {
            this.PlanId = PlanId;
            this.DrugPackageId = DrugPackageId;
            this.MedId = MedId;
            this.QuantityLimit = QuantityLimit;
            this.PriorAuthorization = PriorAuthorization;
            this.StepTherapy = StepTherapy;
            this.Tier = Tier;
        }
        
        /// <summary>
        /// Health Insurance Oversight System id
        /// </summary>
        /// <value>Health Insurance Oversight System id</value>
        [DataMember(Name="plan_id", EmitDefaultValue=false)]
        public string PlanId { get; set; }
        /// <summary>
        /// NDC package code
        /// </summary>
        /// <value>NDC package code</value>
        [DataMember(Name="drug_package_id", EmitDefaultValue=false)]
        public string DrugPackageId { get; set; }
        /// <summary>
        /// Med ID
        /// </summary>
        /// <value>Med ID</value>
        [DataMember(Name="med_id", EmitDefaultValue=false)]
        public int? MedId { get; set; }
        /// <summary>
        /// Quantity limit exists
        /// </summary>
        /// <value>Quantity limit exists</value>
        [DataMember(Name="quantity_limit", EmitDefaultValue=false)]
        public bool? QuantityLimit { get; set; }
        /// <summary>
        /// Prior authorization required
        /// </summary>
        /// <value>Prior authorization required</value>
        [DataMember(Name="prior_authorization", EmitDefaultValue=false)]
        public bool? PriorAuthorization { get; set; }
        /// <summary>
        /// Step Treatment required
        /// </summary>
        /// <value>Step Treatment required</value>
        [DataMember(Name="step_therapy", EmitDefaultValue=false)]
        public bool? StepTherapy { get; set; }
        /// <summary>
        /// Tier Name
        /// </summary>
        /// <value>Tier Name</value>
        [DataMember(Name="tier", EmitDefaultValue=false)]
        public string Tier { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DrugCoverage {\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  DrugPackageId: ").Append(DrugPackageId).Append("\n");
            sb.Append("  MedId: ").Append(MedId).Append("\n");
            sb.Append("  QuantityLimit: ").Append(QuantityLimit).Append("\n");
            sb.Append("  PriorAuthorization: ").Append(PriorAuthorization).Append("\n");
            sb.Append("  StepTherapy: ").Append(StepTherapy).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DrugCoverage);
        }

        /// <summary>
        /// Returns true if DrugCoverage instances are equal
        /// </summary>
        /// <param name="other">Instance of DrugCoverage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DrugCoverage other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PlanId == other.PlanId ||
                    this.PlanId != null &&
                    this.PlanId.Equals(other.PlanId)
                ) && 
                (
                    this.DrugPackageId == other.DrugPackageId ||
                    this.DrugPackageId != null &&
                    this.DrugPackageId.Equals(other.DrugPackageId)
                ) && 
                (
                    this.MedId == other.MedId ||
                    this.MedId != null &&
                    this.MedId.Equals(other.MedId)
                ) && 
                (
                    this.QuantityLimit == other.QuantityLimit ||
                    this.QuantityLimit != null &&
                    this.QuantityLimit.Equals(other.QuantityLimit)
                ) && 
                (
                    this.PriorAuthorization == other.PriorAuthorization ||
                    this.PriorAuthorization != null &&
                    this.PriorAuthorization.Equals(other.PriorAuthorization)
                ) && 
                (
                    this.StepTherapy == other.StepTherapy ||
                    this.StepTherapy != null &&
                    this.StepTherapy.Equals(other.StepTherapy)
                ) && 
                (
                    this.Tier == other.Tier ||
                    this.Tier != null &&
                    this.Tier.Equals(other.Tier)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PlanId != null)
                    hash = hash * 59 + this.PlanId.GetHashCode();
                if (this.DrugPackageId != null)
                    hash = hash * 59 + this.DrugPackageId.GetHashCode();
                if (this.MedId != null)
                    hash = hash * 59 + this.MedId.GetHashCode();
                if (this.QuantityLimit != null)
                    hash = hash * 59 + this.QuantityLimit.GetHashCode();
                if (this.PriorAuthorization != null)
                    hash = hash * 59 + this.PriorAuthorization.GetHashCode();
                if (this.StepTherapy != null)
                    hash = hash * 59 + this.StepTherapy.GetHashCode();
                if (this.Tier != null)
                    hash = hash * 59 + this.Tier.GetHashCode();
                return hash;
            }
        }
    }

}
