/* 
 * Vericred API
 *
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
<cost-share>     ::= <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> <tier-limit> "/" <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> "|" <benefit-limit>
<tier>           ::= "In-Network:" | "In-Network-Tier-2:" | "Out-of-Network:"
<opt-num-prefix> ::= "first" <num> <unit> | ""
<unit>           ::= "day(s)" | "visit(s)" | "exam(s)" | "item(s)"
<value>          ::= <ddct_moop> | <copay> | <coinsurance> | <compound> | "unknown" | "Not Applicable"
<compound>       ::= <copay> <deductible> "then" <coinsurance> <deductible> | <copay> <deductible> "then" <copay> <deductible> | <coinsurance> <deductible> "then" <coinsurance> <deductible>
<copay>          ::= "$" <num>
<coinsurace>     ::= <num> "%"
<ddct_moop>      ::= <copay> | "Included in Medical" | "Unlimited"
<opt-per-unit>   ::= "per day" | "per visit" | "per stay" | ""
<deductible>     ::= "before deductible" | "after deductible" | ""
<tier-limit>     ::= ", " <limit> | ""
<benefit-limit>  ::= <limit> | ""
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Vericred.Model
{
    /// <summary>
    /// Pricing
    /// </summary>
    [DataContract]
    public partial class Pricing :  IEquatable<Pricing>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pricing" /> class.
        /// </summary>
        /// <param name="Age">Age of applicant.</param>
        /// <param name="EffectiveDate">Effective date of plan.</param>
        /// <param name="ExpirationDate">Plan expiration date.</param>
        /// <param name="PlanId">Foreign key to plans.</param>
        /// <param name="PremiumChildOnly">Child-only premium.</param>
        /// <param name="PremiumFamily">Family premium.</param>
        /// <param name="PremiumSingle">Single-person premium.</param>
        /// <param name="PremiumSingleAndChildren">Single person including children premium.</param>
        /// <param name="PremiumSingleAndSpouse">Person with spouse premium.</param>
        /// <param name="PremiumSingleSmoker">Premium for single smoker.</param>
        /// <param name="RatingAreaId">Foreign key to rating areas.</param>
        /// <param name="PremiumSource">Where was this pricing data extracted from?.</param>
        /// <param name="UpdatedAt">Time when pricing was last updated.</param>
        public Pricing(int? Age = null, DateTime? EffectiveDate = null, DateTime? ExpirationDate = null, int? PlanId = null, decimal? PremiumChildOnly = null, decimal? PremiumFamily = null, decimal? PremiumSingle = null, decimal? PremiumSingleAndChildren = null, decimal? PremiumSingleAndSpouse = null, decimal? PremiumSingleSmoker = null, string RatingAreaId = null, string PremiumSource = null, string UpdatedAt = null)
        {
            this.Age = Age;
            this.EffectiveDate = EffectiveDate;
            this.ExpirationDate = ExpirationDate;
            this.PlanId = PlanId;
            this.PremiumChildOnly = PremiumChildOnly;
            this.PremiumFamily = PremiumFamily;
            this.PremiumSingle = PremiumSingle;
            this.PremiumSingleAndChildren = PremiumSingleAndChildren;
            this.PremiumSingleAndSpouse = PremiumSingleAndSpouse;
            this.PremiumSingleSmoker = PremiumSingleSmoker;
            this.RatingAreaId = RatingAreaId;
            this.PremiumSource = PremiumSource;
            this.UpdatedAt = UpdatedAt;
        }
        
        /// <summary>
        /// Age of applicant
        /// </summary>
        /// <value>Age of applicant</value>
        [DataMember(Name="age", EmitDefaultValue=false)]
        public int? Age { get; set; }
        /// <summary>
        /// Effective date of plan
        /// </summary>
        /// <value>Effective date of plan</value>
        [DataMember(Name="effective_date", EmitDefaultValue=false)]
        public DateTime? EffectiveDate { get; set; }
        /// <summary>
        /// Plan expiration date
        /// </summary>
        /// <value>Plan expiration date</value>
        [DataMember(Name="expiration_date", EmitDefaultValue=false)]
        public DateTime? ExpirationDate { get; set; }
        /// <summary>
        /// Foreign key to plans
        /// </summary>
        /// <value>Foreign key to plans</value>
        [DataMember(Name="plan_id", EmitDefaultValue=false)]
        public int? PlanId { get; set; }
        /// <summary>
        /// Child-only premium
        /// </summary>
        /// <value>Child-only premium</value>
        [DataMember(Name="premium_child_only", EmitDefaultValue=false)]
        public decimal? PremiumChildOnly { get; set; }
        /// <summary>
        /// Family premium
        /// </summary>
        /// <value>Family premium</value>
        [DataMember(Name="premium_family", EmitDefaultValue=false)]
        public decimal? PremiumFamily { get; set; }
        /// <summary>
        /// Single-person premium
        /// </summary>
        /// <value>Single-person premium</value>
        [DataMember(Name="premium_single", EmitDefaultValue=false)]
        public decimal? PremiumSingle { get; set; }
        /// <summary>
        /// Single person including children premium
        /// </summary>
        /// <value>Single person including children premium</value>
        [DataMember(Name="premium_single_and_children", EmitDefaultValue=false)]
        public decimal? PremiumSingleAndChildren { get; set; }
        /// <summary>
        /// Person with spouse premium
        /// </summary>
        /// <value>Person with spouse premium</value>
        [DataMember(Name="premium_single_and_spouse", EmitDefaultValue=false)]
        public decimal? PremiumSingleAndSpouse { get; set; }
        /// <summary>
        /// Premium for single smoker
        /// </summary>
        /// <value>Premium for single smoker</value>
        [DataMember(Name="premium_single_smoker", EmitDefaultValue=false)]
        public decimal? PremiumSingleSmoker { get; set; }
        /// <summary>
        /// Foreign key to rating areas
        /// </summary>
        /// <value>Foreign key to rating areas</value>
        [DataMember(Name="rating_area_id", EmitDefaultValue=false)]
        public string RatingAreaId { get; set; }
        /// <summary>
        /// Where was this pricing data extracted from?
        /// </summary>
        /// <value>Where was this pricing data extracted from?</value>
        [DataMember(Name="premium_source", EmitDefaultValue=false)]
        public string PremiumSource { get; set; }
        /// <summary>
        /// Time when pricing was last updated
        /// </summary>
        /// <value>Time when pricing was last updated</value>
        [DataMember(Name="updated_at", EmitDefaultValue=false)]
        public string UpdatedAt { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Pricing {\n");
            sb.Append("  Age: ").Append(Age).Append("\n");
            sb.Append("  EffectiveDate: ").Append(EffectiveDate).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  PremiumChildOnly: ").Append(PremiumChildOnly).Append("\n");
            sb.Append("  PremiumFamily: ").Append(PremiumFamily).Append("\n");
            sb.Append("  PremiumSingle: ").Append(PremiumSingle).Append("\n");
            sb.Append("  PremiumSingleAndChildren: ").Append(PremiumSingleAndChildren).Append("\n");
            sb.Append("  PremiumSingleAndSpouse: ").Append(PremiumSingleAndSpouse).Append("\n");
            sb.Append("  PremiumSingleSmoker: ").Append(PremiumSingleSmoker).Append("\n");
            sb.Append("  RatingAreaId: ").Append(RatingAreaId).Append("\n");
            sb.Append("  PremiumSource: ").Append(PremiumSource).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Pricing);
        }

        /// <summary>
        /// Returns true if Pricing instances are equal
        /// </summary>
        /// <param name="other">Instance of Pricing to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Pricing other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Age == other.Age ||
                    this.Age != null &&
                    this.Age.Equals(other.Age)
                ) && 
                (
                    this.EffectiveDate == other.EffectiveDate ||
                    this.EffectiveDate != null &&
                    this.EffectiveDate.Equals(other.EffectiveDate)
                ) && 
                (
                    this.ExpirationDate == other.ExpirationDate ||
                    this.ExpirationDate != null &&
                    this.ExpirationDate.Equals(other.ExpirationDate)
                ) && 
                (
                    this.PlanId == other.PlanId ||
                    this.PlanId != null &&
                    this.PlanId.Equals(other.PlanId)
                ) && 
                (
                    this.PremiumChildOnly == other.PremiumChildOnly ||
                    this.PremiumChildOnly != null &&
                    this.PremiumChildOnly.Equals(other.PremiumChildOnly)
                ) && 
                (
                    this.PremiumFamily == other.PremiumFamily ||
                    this.PremiumFamily != null &&
                    this.PremiumFamily.Equals(other.PremiumFamily)
                ) && 
                (
                    this.PremiumSingle == other.PremiumSingle ||
                    this.PremiumSingle != null &&
                    this.PremiumSingle.Equals(other.PremiumSingle)
                ) && 
                (
                    this.PremiumSingleAndChildren == other.PremiumSingleAndChildren ||
                    this.PremiumSingleAndChildren != null &&
                    this.PremiumSingleAndChildren.Equals(other.PremiumSingleAndChildren)
                ) && 
                (
                    this.PremiumSingleAndSpouse == other.PremiumSingleAndSpouse ||
                    this.PremiumSingleAndSpouse != null &&
                    this.PremiumSingleAndSpouse.Equals(other.PremiumSingleAndSpouse)
                ) && 
                (
                    this.PremiumSingleSmoker == other.PremiumSingleSmoker ||
                    this.PremiumSingleSmoker != null &&
                    this.PremiumSingleSmoker.Equals(other.PremiumSingleSmoker)
                ) && 
                (
                    this.RatingAreaId == other.RatingAreaId ||
                    this.RatingAreaId != null &&
                    this.RatingAreaId.Equals(other.RatingAreaId)
                ) && 
                (
                    this.PremiumSource == other.PremiumSource ||
                    this.PremiumSource != null &&
                    this.PremiumSource.Equals(other.PremiumSource)
                ) && 
                (
                    this.UpdatedAt == other.UpdatedAt ||
                    this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(other.UpdatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Age != null)
                    hash = hash * 59 + this.Age.GetHashCode();
                if (this.EffectiveDate != null)
                    hash = hash * 59 + this.EffectiveDate.GetHashCode();
                if (this.ExpirationDate != null)
                    hash = hash * 59 + this.ExpirationDate.GetHashCode();
                if (this.PlanId != null)
                    hash = hash * 59 + this.PlanId.GetHashCode();
                if (this.PremiumChildOnly != null)
                    hash = hash * 59 + this.PremiumChildOnly.GetHashCode();
                if (this.PremiumFamily != null)
                    hash = hash * 59 + this.PremiumFamily.GetHashCode();
                if (this.PremiumSingle != null)
                    hash = hash * 59 + this.PremiumSingle.GetHashCode();
                if (this.PremiumSingleAndChildren != null)
                    hash = hash * 59 + this.PremiumSingleAndChildren.GetHashCode();
                if (this.PremiumSingleAndSpouse != null)
                    hash = hash * 59 + this.PremiumSingleAndSpouse.GetHashCode();
                if (this.PremiumSingleSmoker != null)
                    hash = hash * 59 + this.PremiumSingleSmoker.GetHashCode();
                if (this.RatingAreaId != null)
                    hash = hash * 59 + this.RatingAreaId.GetHashCode();
                if (this.PremiumSource != null)
                    hash = hash * 59 + this.PremiumSource.GetHashCode();
                if (this.UpdatedAt != null)
                    hash = hash * 59 + this.UpdatedAt.GetHashCode();
                return hash;
            }
        }
    }

}
