/* 
 * Vericred API
 *
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Vericred.Model
{
    /// <summary>
    /// RequestProvidersSearch
    /// </summary>
    [DataContract]
    public partial class RequestProvidersSearch :  IEquatable<RequestProvidersSearch>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestProvidersSearch" /> class.
        /// </summary>
        /// <param name="AcceptsInsurance">Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true.</param>
        /// <param name="HiosIds">List of HIOS ids.</param>
        /// <param name="Page">Page number.</param>
        /// <param name="PerPage">Number of records to return per page.</param>
        /// <param name="Radius">Radius (in miles) to use to limit results.</param>
        /// <param name="SearchTerm">String to search by.</param>
        /// <param name="ZipCode">Zip Code to search near.</param>
        /// <param name="Type">Either organization or individual.</param>
        public RequestProvidersSearch(bool? AcceptsInsurance = null, List<string> HiosIds = null, int? Page = null, int? PerPage = null, int? Radius = null, string SearchTerm = null, string ZipCode = null, string Type = null)
        {
            this.AcceptsInsurance = AcceptsInsurance;
            this.HiosIds = HiosIds;
            this.Page = Page;
            this.PerPage = PerPage;
            this.Radius = Radius;
            this.SearchTerm = SearchTerm;
            this.ZipCode = ZipCode;
            this.Type = Type;
        }
        
        /// <summary>
        /// Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true
        /// </summary>
        /// <value>Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true</value>
        [DataMember(Name="accepts_insurance", EmitDefaultValue=false)]
        public bool? AcceptsInsurance { get; set; }
        /// <summary>
        /// List of HIOS ids
        /// </summary>
        /// <value>List of HIOS ids</value>
        [DataMember(Name="hios_ids", EmitDefaultValue=false)]
        public List<string> HiosIds { get; set; }
        /// <summary>
        /// Page number
        /// </summary>
        /// <value>Page number</value>
        [DataMember(Name="page", EmitDefaultValue=false)]
        public int? Page { get; set; }
        /// <summary>
        /// Number of records to return per page
        /// </summary>
        /// <value>Number of records to return per page</value>
        [DataMember(Name="per_page", EmitDefaultValue=false)]
        public int? PerPage { get; set; }
        /// <summary>
        /// Radius (in miles) to use to limit results
        /// </summary>
        /// <value>Radius (in miles) to use to limit results</value>
        [DataMember(Name="radius", EmitDefaultValue=false)]
        public int? Radius { get; set; }
        /// <summary>
        /// String to search by
        /// </summary>
        /// <value>String to search by</value>
        [DataMember(Name="search_term", EmitDefaultValue=false)]
        public string SearchTerm { get; set; }
        /// <summary>
        /// Zip Code to search near
        /// </summary>
        /// <value>Zip Code to search near</value>
        [DataMember(Name="zip_code", EmitDefaultValue=false)]
        public string ZipCode { get; set; }
        /// <summary>
        /// Either organization or individual
        /// </summary>
        /// <value>Either organization or individual</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestProvidersSearch {\n");
            sb.Append("  AcceptsInsurance: ").Append(AcceptsInsurance).Append("\n");
            sb.Append("  HiosIds: ").Append(HiosIds).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PerPage: ").Append(PerPage).Append("\n");
            sb.Append("  Radius: ").Append(Radius).Append("\n");
            sb.Append("  SearchTerm: ").Append(SearchTerm).Append("\n");
            sb.Append("  ZipCode: ").Append(ZipCode).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RequestProvidersSearch);
        }

        /// <summary>
        /// Returns true if RequestProvidersSearch instances are equal
        /// </summary>
        /// <param name="other">Instance of RequestProvidersSearch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestProvidersSearch other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AcceptsInsurance == other.AcceptsInsurance ||
                    this.AcceptsInsurance != null &&
                    this.AcceptsInsurance.Equals(other.AcceptsInsurance)
                ) && 
                (
                    this.HiosIds == other.HiosIds ||
                    this.HiosIds != null &&
                    this.HiosIds.SequenceEqual(other.HiosIds)
                ) && 
                (
                    this.Page == other.Page ||
                    this.Page != null &&
                    this.Page.Equals(other.Page)
                ) && 
                (
                    this.PerPage == other.PerPage ||
                    this.PerPage != null &&
                    this.PerPage.Equals(other.PerPage)
                ) && 
                (
                    this.Radius == other.Radius ||
                    this.Radius != null &&
                    this.Radius.Equals(other.Radius)
                ) && 
                (
                    this.SearchTerm == other.SearchTerm ||
                    this.SearchTerm != null &&
                    this.SearchTerm.Equals(other.SearchTerm)
                ) && 
                (
                    this.ZipCode == other.ZipCode ||
                    this.ZipCode != null &&
                    this.ZipCode.Equals(other.ZipCode)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AcceptsInsurance != null)
                    hash = hash * 59 + this.AcceptsInsurance.GetHashCode();
                if (this.HiosIds != null)
                    hash = hash * 59 + this.HiosIds.GetHashCode();
                if (this.Page != null)
                    hash = hash * 59 + this.Page.GetHashCode();
                if (this.PerPage != null)
                    hash = hash * 59 + this.PerPage.GetHashCode();
                if (this.Radius != null)
                    hash = hash * 59 + this.Radius.GetHashCode();
                if (this.SearchTerm != null)
                    hash = hash * 59 + this.SearchTerm.GetHashCode();
                if (this.ZipCode != null)
                    hash = hash * 59 + this.ZipCode.GetHashCode();
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                return hash;
            }
        }
    }

}
